# Generated by Django 5.2.7 on 2025-10-17 13:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('durationdays', models.IntegerField()),
            ],
            options={
                'db_table': 'SubscriptionTypes',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('passport_series', models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Passport series must be exactly 4 digits.', regex='^[0-9]{4}$')])),
                ('passport_number', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Passport number must be exactly 6 digits.', regex='^[0-9]{6}$')])),
                ('date_of_issue', models.DateField(blank=True, null=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='clientservice.roles')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('middlename', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('theme', models.BooleanField(default=False)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='clientservice.users')),
            ],
            options={
                'db_table': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='UserActionsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('actiondate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientservice.users')),
            ],
            options={
                'db_table': 'UserActionsLog',
            },
        ),
        migrations.CreateModel(
            name='TrainingPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(db_column='client_id', on_delete=django.db.models.deletion.CASCADE, related_name='client_plans', to='clientservice.users')),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.CASCADE, related_name='trainer_plans', to='clientservice.users')),
            ],
            options={
                'db_table': 'TrainingPlans',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('subscriptiontype', models.ForeignKey(db_column='subscriptiontype_id', on_delete=django.db.models.deletion.CASCADE, to='clientservice.subscriptiontypes')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='clientservice.users')),
            ],
            options={
                'db_table': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('maxclient', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.CASCADE, to='clientservice.users')),
            ],
            options={
                'db_table': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ClassClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='clientservice.classes')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='clientservice.users')),
            ],
            options={
                'db_table': 'ClassClient',
                'unique_together': {('class_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentdate', models.DateTimeField(auto_now_add=True)),
                ('classclient', models.ForeignKey(blank=True, db_column='classclient_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientservice.classclient')),
                ('subscription', models.ForeignKey(blank=True, db_column='subscription_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientservice.subscriptions')),
            ],
            options={
                'db_table': 'Payments',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('subscription__isnull', False), ('classclient__isnull', True)), models.Q(('subscription__isnull', True), ('classclient__isnull', False)), _connector='OR'), name='check_payment_type')],
            },
        ),
        migrations.CreateModel(
            name='TrainerSpecializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('trainer', models.ForeignKey(db_column='trainer_id', on_delete=django.db.models.deletion.CASCADE, to='clientservice.users')),
            ],
            options={
                'db_table': 'TrainerSpecializations',
                'unique_together': {('trainer', 'specialization')},
            },
        ),
    ]
