# Generated by Django 5.2.7 on 2025-10-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientservice', '0004_alter_userprofiles_user_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/%d/', verbose_name='Аватар'),
        ),
    ]
