# Generated by Django 5.2.7 on 2025-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientservice', '0005_alter_userprofiles_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontypes',
            name='fitness_consultation',
            field=models.BooleanField(default=False, verbose_name='Фитнес-консультация'),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='freeze_days',
            field=models.IntegerField(default=0, verbose_name='Дни заморозки'),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='group_classes',
            field=models.BooleanField(default=False, verbose_name='Групповые занятия'),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='guest_visits',
            field=models.IntegerField(default=0, verbose_name='Гостевые визиты'),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='gym_access',
            field=models.BooleanField(default=False, verbose_name='Тренажерный зал'),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='locker_room',
            field=models.BooleanField(default=False, verbose_name='Раздевалка'),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='nutrition_consultation',
            field=models.BooleanField(default=False, verbose_name='Консультация по питанию'),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='personal_training',
            field=models.BooleanField(default=False, verbose_name='Персональные тренировки'),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='pool_access',
            field=models.BooleanField(default=False, verbose_name='Бассейн'),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='spa_access',
            field=models.BooleanField(default=False, verbose_name='СПА зона'),
        ),
        migrations.AddField(
            model_name='subscriptiontypes',
            name='towel_service',
            field=models.BooleanField(default=False, verbose_name='Полотенце'),
        ),
    ]
