# Generated by Django 5.2.8 on 2025-11-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientservice', '0006_subscriptiontypes_fitness_consultation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractionslog',
            options={'ordering': ['-actiondate']},
        ),
        migrations.AddField(
            model_name='useractionslog',
            name='action_type',
            field=models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Обновление'), ('DELETE', 'Удаление'), ('LOGIN', 'Вход в систему'), ('LOGOUT', 'Выход из системы'), ('SYSTEM', 'Системное действие')], default='SYSTEM', max_length=10),
        ),
        migrations.AddField(
            model_name='useractionslog',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractionslog',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractionslog',
            name='object_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractionslog',
            name='user_full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
