# Generated by Django 5.2.8 on 2025-11-08 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientservice', '0008_trainerspecializationsfor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainerSpecializationsFor',
            new_name='TrainerSpecializations2',
        ),
        migrations.AlterModelTable(
            name='trainerspecializations2',
            table='TrainerSpecializations2',
        ),
    ]
