# Generated by Django 5.2.8 on 2025-11-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientservice', '0009_rename_trainerspecializationsfor_trainerspecializations2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='TrainerSpecializations2',
        ),
    ]
