# Generated by Django 5.2.8 on 2025-11-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientservice', '0010_delete_roles_delete_trainerspecializations2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontypes',
            name='fitness_consultation',
        ),
        migrations.RemoveField(
            model_name='subscriptiontypes',
            name='freeze_days',
        ),
        migrations.RemoveField(
            model_name='subscriptiontypes',
            name='group_classes',
        ),
        migrations.RemoveField(
            model_name='subscriptiontypes',
            name='guest_visits',
        ),
        migrations.RemoveField(
            model_name='subscriptiontypes',
            name='personal_training',
        ),
    ]
